In [3]:
# Массив 4x3 со случайными целыми числами (от 1 до 20):
a = rand(1:20,(4,3))

4×3 Matrix{Int64}:
  9   9  18
  6   2  19
  8  12   8
 20   2  11

In [8]:
# Поэлементная сумма:
sum(a)

124

In [9]:
# Поэлементная сумма по столбцам:
sum(a,dims=1)

1×3 Matrix{Int64}:
 43  25  56

In [10]:
# Поэлементная сумма по строкам:
sum(a,dims=2)

4×1 Matrix{Int64}:
 36
 27
 28
 33

In [6]:
# Поэлементное произведение:
prod(a)

4×1 Matrix{Int64}:
 1458
  228
  768
  440

In [11]:
# Поэлементное произведение по столбцам:
prod(a,dims=1)

1×3 Matrix{Int64}:
 8640  432  30096

In [12]:
# Поэлементное произведение по строкам:
prod(a,dims=2)

4×1 Matrix{Int64}:
 1458
  228
  768
  440

In [7]:
# Подключение пакета Statistics:
import Pkg
Pkg.add("Statistics")
using Statistics

    Updating registry at `C:\Users\GlebB\.julia\registries\General.toml`
   Resolving package versions...
    Updating `C:\Users\GlebB\.julia\environments\v1.9\Project.toml`
  [10745b16] + Statistics v1.9.0
  No Changes to `C:\Users\GlebB\.julia\environments\v1.9\Manifest.toml`


4×1 Matrix{Float64}:
 12.0
  9.0
  9.333333333333334
 11.0

In [13]:
# Вычисление среднего значения массива:
mean(a)

10.333333333333334

In [14]:
# Среднее по столбцам:
mean(a,dims=1)

1×3 Matrix{Float64}:
 10.75  6.25  14.0

In [15]:
# Среднее по строкам:
mean(a,dims=2)

4×1 Matrix{Float64}:
 12.0
  9.0
  9.333333333333334
 11.0

In [16]:
# Подключение пакета LinearAlgebra:
import Pkg
Pkg.add("LinearAlgebra")
using LinearAlgebra

   Resolving package versions...
    Updating `C:\Users\GlebB\.julia\environments\v1.9\Project.toml`
  [37e2e46d] + LinearAlgebra
  No Changes to `C:\Users\GlebB\.julia\environments\v1.9\Manifest.toml`


In [19]:
# Массив 4x4 со случайными целыми числами (от 1 до 20):
b = rand(1:20,(4,4))
# Транспонирование:
transpose(b)

4×4 transpose(::Matrix{Int64}) with eltype Int64:
  1  11   6   6
 12   5  14   7
  6  11   5  13
  2  12  14  15

In [20]:
# След матрицы (сумма диагональных элементов):
tr(b)

26

In [18]:
# Извлечение диагональных элементов как массив:
diag(b)

4-element Vector{Int64}:
  8
 12
 18
 15

In [21]:
# Ранг матрицы:
rank(b)

4

In [22]:
# Инверсия матрицы (определение обратной матрицы):
inv(b)

4×4 Matrix{Float64}:
 -0.000289603   0.16044      0.0133217  -0.140747
  0.0643885    -0.00453712   0.0381311  -0.0405445
  0.067381      0.00424751  -0.099527    0.0805097
 -0.088329     -0.0657399    0.0631335   0.0721112

In [23]:
# Определитель матрицы:
det(b)

10359.0

In [24]:
# Псевдобратная функция для прямоугольных матриц:
pinv(a)

3×4 Matrix{Float64}:
 -0.014341   -0.0241341   0.00445983   0.0619098
  0.023717   -0.0373237   0.0767987   -0.030195
  0.0212517   0.0510161  -0.0217465   -0.0161695

In [25]:
# Создание вектора X:
X = [2, 4, -5]
# Вычисление евклидовой нормы:
norm(X)
# Вычисление p-нормы:
p = 1
norm(X,p)

11.0

In [26]:
# Расстояние между двумя векторами X и Y:
X = [2, 4, -5];
Y = [1,-1,3];
norm(X-Y)

9.486832980505138

In [27]:
# Проверка по базовому определению:
sqrt(sum((X-Y).^2))

9.486832980505138

In [28]:
# Угол между двумя векторами:
acos((transpose(X)*Y)/(norm(X)*norm(Y)))

2.4404307889469252

In [29]:
# Создание матрицы:
d = [5 -4 2 ; -1 2 3; -2 1 0]

3×3 Matrix{Int64}:
  5  -4  2
 -1   2  3
 -2   1  0

In [30]:
# Вычисление Евклидовой нормы:
opnorm(d)

7.147682841795258

In [31]:
# Вычисление p-нормы:
p=1
opnorm(d,p)

8.0

In [32]:
# Поворот на 180 градусов:
rot180(d)

3×3 Matrix{Int64}:
 0   1  -2
 3   2  -1
 2  -4   5

In [33]:
# Переворачивание строк:
reverse(d,dims=1)

3×3 Matrix{Int64}:
 -2   1  0
 -1   2  3
  5  -4  2

In [34]:
# Переворачивание столбцов
reverse(d,dims=2)

3×3 Matrix{Int64}:
 2  -4   5
 3   2  -1
 0   1  -2

In [35]:
# Матрица 2x3 со случайными целыми значениями от 1 до 10:
A = rand(1:10,(2,3))

2×3 Matrix{Int64}:
 6  9  10
 8  4  10

In [36]:
# Матрица 3x4 со случайными целыми значениями от 1 до 10:
B = rand(1:10,(3,4))

3×4 Matrix{Int64}:
 9   1  9  10
 4  10  8   3
 6   8  3   1

In [37]:
# Произведение матриц A и B:
A*B

2×4 Matrix{Int64}:
 150  176  156   97
 148  128  134  102

In [38]:
# Единичная матрица 3x3:
Matrix{Int}(I, 3, 3)

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1

In [39]:
# Скалярное произведение векторов X и Y:
X = [2, 4, -5]
Y = [1,-1,3]
dot(X,Y)

-17

In [40]:
# тоже скалярное произведение:
X'Y

-17

In [41]:
# Задаём квадратную матрицу 3x3 со случайными значениями:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.675351  0.298063  0.933472
 0.873562  0.631751  0.686768
 0.264798  0.355774  0.183635

In [42]:
# Задаём единичный вектор:
x = fill(1.0, 3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [43]:
# Задаём вектор b:
b = A*x

3-element Vector{Float64}:
 1.9068863752704455
 2.192080508690627
 0.8042070810272597

In [44]:
# Решение исходного уравнения получаем с помощью функции \
# (убеждаемся, что x - единичный вектор):
A\b

3-element Vector{Float64}:
 1.0000000000000013
 0.9999999999999994
 0.9999999999999993

In [45]:
# LU-факторизация:
Alu = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.773101   1.0       0.0
 0.303124  -0.863039  1.0
U factor:
3×3 Matrix{Float64}:
 0.873562   0.631751  0.686768
 0.0       -0.190344  0.402531
 0.0        0.0       0.322859

In [46]:
# Матрица перестановок:
Alu.P

3×3 Matrix{Float64}:
 0.0  1.0  0.0
 1.0  0.0  0.0
 0.0  0.0  1.0

In [47]:
# Вектор перестановок:
Alu.p

3-element Vector{Int64}:
 2
 1
 3

In [48]:
# Матрица L:
Alu.L

3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.773101   1.0       0.0
 0.303124  -0.863039  1.0

In [49]:
# Матрица U:
Alu.U

3×3 Matrix{Float64}:
 0.873562   0.631751  0.686768
 0.0       -0.190344  0.402531
 0.0        0.0       0.322859

In [50]:
# Решение СЛАУ через матрицу A:
A\b

3-element Vector{Float64}:
 1.0000000000000013
 0.9999999999999994
 0.9999999999999993

In [51]:
# Решение СЛАУ через объект факторизации:
Alu\b

3-element Vector{Float64}:
 1.0000000000000013
 0.9999999999999994
 0.9999999999999993

In [52]:
# Детерминант матрицы A:
det(A)

0.05368420908258649

In [53]:
# Детерминант матрицы A через объект факторизации:
det(Alu)

0.05368420908258649

In [54]:
# QR-факторизация:
Aqr = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.594769   0.607444   0.526557
 -0.769329  -0.240086  -0.592024
 -0.233202  -0.757213   0.610119
R factor:
3×3 Matrix{Float64}:
 -1.13549  -0.74627   -1.12637
  0.0      -0.240014   0.263098
  0.0       0.0        0.196982

In [55]:
# Матрица Q:
Aqr.Q

3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.594769   0.607444   0.526557
 -0.769329  -0.240086  -0.592024
 -0.233202  -0.757213   0.610119

In [56]:
# Матрица R:
Aqr.R

3×3 Matrix{Float64}:
 -1.13549  -0.74627   -1.12637
  0.0      -0.240014   0.263098
  0.0       0.0        0.196982

In [57]:
# Проверка, что матрица Q - ортогональная:
Aqr.Q'*Aqr.Q

3×3 Matrix{Float64}:
 1.0  -1.11022e-16  0.0
 0.0   1.0          2.22045e-16
 0.0   2.22045e-16  1.0

In [58]:
# Симметризация матрицы A:
Asym = A + A'

3×3 Matrix{Float64}:
 1.3507   1.17162  1.19827
 1.17162  1.2635   1.04254
 1.19827  1.04254  0.36727

In [60]:
# Спектральное разложение симметризованной матрицы:
AsymEig = eigen(Asym)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -0.49037528464639485
  0.1423009515620718
  3.3295498969172534
vectors:
3×3 Matrix{Float64}:
 -0.415539   0.643362   -0.642972
 -0.243369  -0.759761   -0.602938
  0.876412   0.0940649  -0.472285

In [61]:
# Собственные значения:
AsymEig.values

3-element Vector{Float64}:
 -0.49037528464639485
  0.1423009515620718
  3.3295498969172534

In [62]:
#Собственные векторы:
AsymEig.vectors

3×3 Matrix{Float64}:
 -0.415539   0.643362   -0.642972
 -0.243369  -0.759761   -0.602938
  0.876412   0.0940649  -0.472285

In [63]:
# Проверяем, что получится единичная матрица:
inv(AsymEig)*Asym

3×3 Matrix{Float64}:
 1.0          -2.66454e-15  -4.44089e-16
 4.13558e-15   1.0           2.20657e-15
 1.77636e-15   2.22045e-15   1.0

In [64]:
# Матрица 1000 х 1000:
n = 1000
A = randn(n,n)

1000×1000 Matrix{Float64}:
  0.19653    -1.28792     1.16627    …  -1.84939    -1.34687     0.0181986
  0.100823   -0.242892   -1.78588       -0.951881   -0.694639    1.01759
  0.356048    0.687924    0.0288233     -0.81331    -1.04784     2.1041
  0.839306    1.17316     0.102227      -2.14399    -0.172797    0.692587
 -0.0264909   0.0640003  -0.28165        0.938568   -0.516024    0.135838
  0.839222    0.541828    1.81463    …  -0.257015    0.206856    1.07932
 -1.13509    -0.656688    0.958005      -0.872888   -0.0603781  -0.583505
  0.0969855  -1.10011     0.414148      -0.0181358  -0.0280408  -0.655324
 -0.215069    0.685932    0.843887       1.08668    -0.308307   -0.0473633
 -0.0640355   0.0312235  -0.406964      -2.2979     -0.0320142   0.0212742
 -0.895282   -0.517428   -0.979889   …  -0.190308    0.544045    0.286461
 -0.467473    0.118284    2.29478        2.13171    -1.04756     0.552324
  1.01328     0.832668   -0.358916      -1.3213     -1.72488     0.69898
  ⋮          

In [65]:
# Симметризация матрицы:
Asym = A + A'

1000×1000 Matrix{Float64}:
  0.393061  -1.1871     1.52232    …  -2.68199   -1.09688    -1.75511
 -1.1871    -0.485784  -1.09796        0.134448  -1.12184     1.8987
  1.52232   -1.09796    0.0576466     -2.16454   -0.632841    2.6184
  2.20254    2.12601    1.37919       -0.86109    1.38753     1.14129
  1.14361    0.670914  -0.0388096     -0.222059  -0.324271    0.174666
  0.4213     0.237232   3.36525    …   0.574236   0.0863073   1.37996
 -1.12982   -0.138938   0.183372      -0.725398   0.580001   -0.369564
  0.907652  -2.17058    0.748957      -1.53514   -0.627687   -0.127403
  0.43601   -0.342293   0.25039        1.02085   -0.711883    0.583164
  0.547735  -0.316938  -0.495361      -0.510295   0.578657    0.0241491
  0.127273   0.215779   0.0729088  …   1.1158     2.47708     0.760371
 -0.175972   1.07572    2.89464        2.63094   -1.5264     -0.396812
  2.18405   -0.469264   1.93446       -2.98784   -3.06913     0.64797
  ⋮                                ⋱                     

In [66]:
# Проверка, является ли матрица симметричной:
issymmetric(Asym)

true

In [67]:
# Добавление шума:
Asym_noisy = copy(Asym)
Asym_noisy[1,2] += 5eps()

-1.1871005162529327

In [68]:
# Проверка, является ли матрица симметричной:
issymmetric(Asym_noisy)

false

In [69]:
# Явно указываем, что матрица является симметричной:
Asym_explicit = Symmetric(Asym_noisy)

1000×1000 Symmetric{Float64, Matrix{Float64}}:
  0.393061  -1.1871     1.52232    …  -2.68199   -1.09688    -1.75511
 -1.1871    -0.485784  -1.09796        0.134448  -1.12184     1.8987
  1.52232   -1.09796    0.0576466     -2.16454   -0.632841    2.6184
  2.20254    2.12601    1.37919       -0.86109    1.38753     1.14129
  1.14361    0.670914  -0.0388096     -0.222059  -0.324271    0.174666
  0.4213     0.237232   3.36525    …   0.574236   0.0863073   1.37996
 -1.12982   -0.138938   0.183372      -0.725398   0.580001   -0.369564
  0.907652  -2.17058    0.748957      -1.53514   -0.627687   -0.127403
  0.43601   -0.342293   0.25039        1.02085   -0.711883    0.583164
  0.547735  -0.316938  -0.495361      -0.510295   0.578657    0.0241491
  0.127273   0.215779   0.0729088  …   1.1158     2.47708     0.760371
 -0.175972   1.07572    2.89464        2.63094   -1.5264     -0.396812
  2.18405   -0.469264   1.93446       -2.98784   -3.06913     0.64797
  ⋮                                ⋱ 

In [70]:
import Pkg
Pkg.add("BenchmarkTools")
using BenchmarkTools
# Оценка эффективности выполнения операции по нахождению
# собственных значений симметризованной матрицы:
@btime eigvals(Asym);

   Resolving package versions...
  No Changes to `C:\Users\GlebB\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\GlebB\.julia\environments\v1.9\Manifest.toml`


  373.472 ms (11 allocations: 7.99 MiB)


In [71]:
# Оценка эффективности выполнения операции по нахождению
# собственных значений зашумлённой матрицы:
@btime eigvals(Asym_noisy);

  1.158 s (14 allocations: 7.93 MiB)


In [72]:
# Оценка эффективности выполнения операции по нахождению
# собственных значений зашумлённой матрицы,
# для которой явно указано, что она симметричная:
@btime eigvals(Asym_explicit);

  251.271 ms (11 allocations: 7.99 MiB)


In [73]:
# Трёхдиагональная матрица 1000000 х 1000000:
n = 1000000;
A = SymTridiagonal(randn(n), randn(n-1))

1000000×1000000 SymTridiagonal{Float64, Vector{Float64}}:
 0.308917  1.67869    ⋅         ⋅        …    ⋅          ⋅          ⋅ 
 1.67869   0.62622   0.829802   ⋅             ⋅          ⋅          ⋅ 
  ⋅        0.829802  1.77733   0.720879       ⋅          ⋅          ⋅ 
  ⋅         ⋅        0.720879  1.6302         ⋅          ⋅          ⋅ 
  ⋅         ⋅         ⋅        0.51027        ⋅          ⋅          ⋅ 
  ⋅         ⋅         ⋅         ⋅        …    ⋅          ⋅          ⋅ 
  ⋅         ⋅         ⋅         ⋅             ⋅          ⋅          ⋅ 
  ⋅         ⋅         ⋅         ⋅             ⋅          ⋅          ⋅ 
  ⋅         ⋅         ⋅         ⋅             ⋅          ⋅          ⋅ 
  ⋅         ⋅         ⋅         ⋅             ⋅          ⋅          ⋅ 
  ⋅         ⋅         ⋅         ⋅        …    ⋅          ⋅          ⋅ 
  ⋅         ⋅         ⋅         ⋅             ⋅          ⋅          ⋅ 
  ⋅         ⋅         ⋅         ⋅             ⋅          ⋅          ⋅ 
 ⋮                 

In [74]:
# Оценка эффективности выполнения операции по нахождению
# собственных значений:
@btime eigmax(A)

  740.392 ms (17 allocations: 183.11 MiB)


6.52034195883315

In [75]:
# Матрица с рациональными элементами:
Arational = Matrix{Rational{BigInt}}(rand(1:10, 3, 3))/10

3×3 Matrix{Rational{BigInt}}:
 1//1   3//5   1//10
 7//10  7//10  9//10
 3//5   3//10  7//10

In [76]:
# Единичный вектор:
x = fill(1, 3)

3-element Vector{Int64}:
 1
 1
 1

In [77]:
# Задаём вектор b:
b = Arational*x

3-element Vector{Rational{BigInt}}:
 17//10
 23//10
  8//5

In [78]:
# Решение исходного уравнения получаем с помощью функции \
# (убеждаемся, что x - единичный вектор):
Arational\b

3-element Vector{Rational{BigInt}}:
 1//1
 1//1
 1//1

In [79]:
# LU-разложение:
lu(Arational)

LU{Rational{BigInt}, Matrix{Rational{BigInt}}, Vector{Int64}}
L factor:
3×3 Matrix{Rational{BigInt}}:
 1//1    0//1   0//1
 7//10   1//1   0//1
 3//5   -3//14  1//1
U factor:
3×3 Matrix{Rational{BigInt}}:
 1//1  3//5     1//10
 0//1  7//25   83//100
 0//1  0//1   229//280

In [81]:
v = [3, 5, 2, 9]
dot_v = dot(v, v)

119

In [82]:
outer_v = v * v'

4×4 Matrix{Int64}:
  9  15   6  27
 15  25  10  45
  6  10   4  18
 27  45  18  81

In [91]:
# Left - лево, Right - право
L1 = [1 1; 1 -1]
R1 = [2; 3]

2-element Vector{Int64}:
 2
 3

In [102]:
L1\R1

2-element Vector{Float64}:
  2.5
 -0.5

In [93]:
L2 = [1 1; 2 2]
R2 = [2; 4]

2-element Vector{Int64}:
 2
 4

In [103]:
L2\R2

LoadError: SingularException(2)

In [95]:
L3 = [1 1; 2 2]
R3 = [2; 5]

2-element Vector{Int64}:
 2
 5

In [104]:
L3\R3

LoadError: SingularException(2)

In [97]:
L4 = [1 1; 2 2; 3 3]
R4 = [1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

In [105]:
L4\R4

2-element Vector{Float64}:
 0.4999999999999999
 0.5

In [99]:
L5 = [1 1; 2 1; 1 -1]
R5 = [2; 1; 3]

3-element Vector{Int64}:
 2
 1
 3

In [106]:
L5\R5

2-element Vector{Float64}:
  1.5000000000000004
 -0.9999999999999997

In [101]:
L6 = [1 1; 2 1; 3 2]
R6 = [2; 1; 3]

3-element Vector{Int64}:
 2
 1
 3

In [108]:
L6\R6

2-element Vector{Float64}:
 -0.9999999999999989
  2.9999999999999982

In [109]:
L7 = [1 1 1; 1 -1 -2]
R7 = [2; 3]
L7\R7

3-element Vector{Float64}:
  2.2142857142857144
  0.35714285714285704
 -0.5714285714285712

In [110]:
L8 = [1 1 1; 2 2 -3; 3 1 1]
R8 = [2; 4; 1]
L8\R8

3-element Vector{Float64}:
 -0.5
  2.5
  0.0

In [111]:
L9 = [1 1 1; 1 1 2; 2 2 3]
R9 = [1; 0; 1]
L9\R9

LoadError: SingularException(2)

In [112]:
L10 = [1 1 1; 1 1 2; 2 2 3]
R10 = [1; 0; 0]
L10\R10

LoadError: SingularException(2)

In [115]:
function dia(mat)
    simm = mat + mat'
    razsimm = eigen(simm)
    return inv(razsimm.vectors) * mat * razsimm.vectors
end

dia (generic function with 1 method)

In [116]:
mat1 = [1 -2; -2 1]
dia(mat1)

2×2 Matrix{Float64}:
 -1.0  0.0
  0.0  3.0

In [117]:
mat2 = [1 -2; -2 3]
dia(mat2)

2×2 Matrix{Float64}:
 -0.236068     3.46945e-16
  4.44089e-16  4.23607

In [118]:
mat3 = [1 -2 0; -2 1 2; 0 2 0]
dia(mat3)

3×3 Matrix{Float64}:
 -2.14134       3.55271e-15  -1.9984e-15
  3.38618e-15   0.515138      1.11022e-16
 -6.66134e-16  -4.44089e-16   3.6262

In [119]:
([1 -2; -2 1])^10

2×2 Matrix{Int64}:
  29525  -29524
 -29524   29525

In [120]:
sqrt([5 -2; -2 5])

2×2 Matrix{Float64}:
  2.1889   -0.45685
 -0.45685   2.1889

In [121]:
([1 -2; -2 1])^(1/3)

2×2 Symmetric{ComplexF64, Matrix{ComplexF64}}:
  0.971125+0.433013im  -0.471125+0.433013im
 -0.471125+0.433013im   0.971125+0.433013im

In [122]:
sqrt([1 2; 2 3])

2×2 Matrix{ComplexF64}:
 0.568864+0.351578im  0.920442-0.217287im
 0.920442-0.217287im   1.48931+0.134291im

In [123]:
A = [140 97 74 168 131; 97 106 89 131 36; 74 89 152 144 71; 168 131 144 54 142; 131 36 71 142 36]
val = eigvals(A)

5-element Vector{Float64}:
 -128.49322764802145
  -55.887784553056875
   42.7521672793189
   87.16111477514521
  542.4677301466143

In [124]:
@btime eigvals(A)

  3.700 μs (10 allocations: 2.59 KiB)


5-element Vector{Float64}:
 -128.49322764802145
  -55.887784553056875
   42.7521672793189
   87.16111477514521
  542.4677301466143

In [126]:
N = zeros(4, 4)
@btime for i in 1:1:4
    N[i, i] = val[i]
end
N

  241.646 ns (4 allocations: 64 bytes)


4×4 Matrix{Float64}:
 -128.493    0.0      0.0      0.0
    0.0    -55.8878   0.0      0.0
    0.0      0.0     42.7522   0.0
    0.0      0.0      0.0     87.1611

In [127]:
Alu = lu(A)
@btime Alu.L

  147.407 ns (1 allocation: 256 bytes)


5×5 Matrix{Float64}:
 1.0        0.0        0.0       0.0       0.0
 0.779762   1.0        0.0       0.0       0.0
 0.440476  -0.47314    1.0       0.0       0.0
 0.833333   0.183929  -0.556312  1.0       0.0
 0.577381  -0.459012  -0.189658  0.897068  1.0

In [128]:
function matr(mat, s)
    ans = ""
    P = [1 0; 0 1]
    K = rand(0:100, s)
    H = P - mat
    T = H\K
    for i in 1:1:s
        if T[i] < 0
            ans = "no"
            break
        else
            ans = "yes"
        end
    end
    return ans
end

matr (generic function with 1 method)

In [129]:
mat1 = [1 2; 3 4]
matr(mat1, 2)

"no"

In [130]:
mat2 = ([1 2; 3 4])*(1/2)
matr(mat2, 2)

"no"

In [131]:
mat3 = ([1 2; 3 4])*(1/10)
matr(mat3, 2)

"yes"