In [1]:
# пока n<10 прибавить к n единицу и распечатать значение:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [5]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [7]:
for n in 1:2:10
    println(n)
end

1
3
5
7
9


In [8]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
for friend in myfriends
    println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [9]:
# инициализация массива m x n из нулей:
m, n = 5, 5
A = fill(0, (m, n))

5×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [10]:
# формирование массива, в котором значение каждой записи
# является суммой индексов строки и столбца:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [11]:
# инициализация массива m x n из нулей:
B = fill(0, (m, n))

for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [13]:
# Ещё одна реализация этого же примера:
C = [i + j for i in 1:m, j in 1:n]
C

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [21]:
# используем `&&` для реализации операции "AND"
# операция % вычисляет остаток от деления
N = 3

if (N % 3 == 0) && (N % 5 == 0)
    println("FizzBuzz")
elseif N % 3 == 0
    println("Fizz")
elseif N % 5 == 0
    println("Buzz")
else
    println(N)
end

Fizz


In [22]:
x = 5
y = 10
(x > y) ? x : y

10

In [24]:
function sayhi(name)
    println("Hi $name, it's great to see you!")
end
sayhi("Gleb")

Hi Gleb, it's great to see you!


In [25]:
function f(x)
    x^2
end
f(3)

9

In [28]:
sayhi2(name) = println("Hi $name, it's great to see you!")
sayhi2("Glebushka")

Hi Glebushka, it's great to see you!


In [29]:
f2(x) = x^2
f2(4)

16

In [38]:
sayhi3 = name -> println("Hi $name, it's great to see you!")
sayhi2("Glebati")

Hi Glebati, it's great to see you!


In [39]:
#f3(x) = x -> x^2
#f3(5)

In [43]:
# задаём массив v:
v = [3, 5, 2]
sort(v)
v

3-element Vector{Int64}:
 3
 5
 2

In [44]:
sort!(v)
v

3-element Vector{Int64}:
 2
 3
 5

In [46]:
f(x) = x^2
map(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [47]:
x -> x^3
map(x -> x^3, [1, 2, 3])

3-element Vector{Int64}:
  1
  8
 27

In [48]:
# задаём матрицу A
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [49]:
# вызываем функцию f возведения в квадрат
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [50]:
B = f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [51]:
A .+ 2 .* f.(A) ./ A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [52]:
@. A + 2 * f(A) / A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [53]:
broadcast(x -> x + 2 * f(x) / x, A)

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [3]:
import Pkg
Pkg.add("Example")

   Resolving package versions...
  No Changes to `C:\Users\GlebB\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\GlebB\.julia\environments\v1.9\Manifest.toml`


In [4]:
Pkg.add("Colors")
using Colors

   Resolving package versions...
  No Changes to `C:\Users\GlebB\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\GlebB\.julia\environments\v1.9\Manifest.toml`


In [5]:
palette = distinguishable_colors(100)

In [57]:
rand(palette, 3, 3)

In [59]:
i = 1
while i <= 100
    println(i)
    println(i^2)
    i += 1
end

1
1
2
4
3
9
4
16
5
25
6
36
7
49
8
64
9
81
10
100
11
121
12
144
13
169
14
196
15
225
16
256
17
289
18
324
19
361
20
400
21
441
22
484
23
529
24
576
25
625
26
676
27
729
28
784
29
841
30
900
31
961
32
1024
33
1089
34
1156
35
1225
36
1296
37
1369
38
1444
39
1521
40
1600
41
1681
42
1764
43
1849
44
1936
45
2025
46
2116
47
2209
48
2304
49
2401
50
2500
51
2601
52
2704
53
2809
54
2916
55
3025
56
3136
57
3249
58
3364
59
3481
60
3600
61
3721
62
3844
63
3969
64
4096
65
4225
66
4356
67
4489
68
4624
69
4761
70
4900
71
5041
72
5184
73
5329
74
5476
75
5625
76
5776
77
5929
78
6084
79
6241
80
6400
81
6561
82
6724
83
6889
84
7056
85
7225
86
7396
87
7569
88
7744
89
7921
90
8100
91
8281
92
8464
93
8649
94
8836
95
9025
96
9216
97
9409
98
9604
99
9801
100
10000


In [60]:
for i in 1:1:100
    println(i)
end

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [61]:
squares = Dict{Int64, Int64}()
for i in 1:1:100
    push!(squares, i => i^2)
end
pairs(squares)

Dict{Int64, Int64} with 100 entries:
  5  => 25
  56 => 3136
  35 => 1225
  55 => 3025
  60 => 3600
  30 => 900
  32 => 1024
  6  => 36
  67 => 4489
  45 => 2025
  73 => 5329
  64 => 4096
  90 => 8100
  4  => 16
  13 => 169
  54 => 2916
  63 => 3969
  86 => 7396
  91 => 8281
  62 => 3844
  58 => 3364
  52 => 2704
  12 => 144
  28 => 784
  75 => 5625
  ⋮  => ⋮

In [64]:
N = []
for i in 1:1:100
    append!(N, i)
end

squares_arr = []
i = 1
while i <= length(N)
    append!(squares_arr, N[i]^2)
    i += 1
end
squares_arr

100-element Vector{Any}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

In [65]:
N = 7

if N % 2 == 0
    println("Четное")
else
    println("Нечетное")
end

Нечетное


In [67]:
N = 8
(N % 2 == 0) ? println("Четное") : println("Нечетное")

Четное


In [68]:
function add_one(A)
    A + 1
end
add_one(2)

3

In [75]:
broadcast(x -> x + 1, A)

3×3 Matrix{Int64}:
 2  3   4
 5  6   7
 8  9  10

In [76]:
A = [1 1 3; 5 2 6; -2 -1 -3]

3×3 Matrix{Int64}:
  1   1   3
  5   2   6
 -2  -1  -3

In [77]:
A^3

3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  0

In [80]:
for i in 7:1:9
    A[i] += A[i-3]
end
A

3×3 Matrix{Int64}:
  1   1   6
  5   2  12
 -2  -1  -6

In [6]:
B = Array{Int32, 2}(undef, 15, 3)
for i in 1:1:15
    B[i, 1] = 10
    B[i, 2] = -10
    B[i, 3] = 10
end
B

15×3 Matrix{Int32}:
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10

In [7]:
C = (B')*B
C

3×3 Matrix{Int32}:
  1500  -1500   1500
 -1500   1500  -1500
  1500  -1500   1500

In [8]:
Z = zeros(Int64, 6, 6)

6×6 Matrix{Int64}:
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

In [9]:
E = ones(Int64, 6, 6)

6×6 Matrix{Int64}:
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1

In [14]:
Z1 = zeros(Int64, 6, 6)
for i in 1:1:6
    if i != 1
        Z1[i, i - 1] = E[i, i - 1]
    end
    if i != 6
        Z1[i, i + 1] = E[i, i + 1]
    end
end
Z1

6×6 Matrix{Int64}:
 0  1  0  0  0  0
 1  0  1  0  0  0
 0  1  0  1  0  0
 0  0  1  0  1  0
 0  0  0  1  0  1
 0  0  0  0  1  0

In [16]:
Z2 = zeros(Int64, 6, 6)
for i in 1:1:6
    Z2[i,i] = 1
    if(i+2 <= 6) Z2[i, i + 2] = E[i, i + 2] end
    if(i-2 >= 1) Z2[i, i - 2] = E[i, i - 2] end
end
Z2

6×6 Matrix{Int64}:
 1  0  1  0  0  0
 0  1  0  1  0  0
 1  0  1  0  1  0
 0  1  0  1  0  1
 0  0  1  0  1  0
 0  0  0  1  0  1

In [17]:
Z3 = zeros(Int64, 6, 6)
for i in 1:1:6
    Z3[i,7-i] = 1
    if((7-i+2) <= 6) Z3[i, 9 - i] = E[i, 9 - i] end
    if((7-i-2) >= 1) Z3[i, 5 - i] = E[i, 5 - i] end
end
Z3

6×6 Matrix{Int64}:
 0  0  0  1  0  1
 0  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  0
 1  0  1  0  0  0

In [19]:
Z4 = zeros(Int64, 6, 6)
for i in 1:1:6
    Z4[i,i] = 1
    if(i+2 <= 6) Z4[i, i + 2] = E[i, i + 2] end
    if(i-2 >= 1) Z4[i, i - 2] = E[i, i - 2] end
    if(i+4 <= 6) Z4[i, i + 4] = E[i, i + 4] end
    if(i-4 >= 1) Z4[i, i - 4] = E[i, i - 4] end
end
Z4

6×6 Matrix{Int64}:
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1

In [20]:
function1 = 0
for i in 1:1:20
    for j in 1:1:5
        function1 += (i^4)/(3+j)
    end
end
println(function1)

639215.2833333334


In [21]:
function2 = 0
for i in 1:1:20
    for j in 1:1:5
        function2 += (i^4)/(3+i*j)
    end
end
println(function2)

89912.02146097136
